@echo off
cd /d %~dp0
echo Starting VibeForge...
if not exist node_modules (
  echo Installing dependencies...
  cmd /c "npm install"
)
echo Rebuilding native modules...
cmd /c "npm run rebuild"
echo Launching VibeForge (window should appear on your desktop)...
npx --yes electron@30.5.1 .
pause